### ISSUE TITLE
Erro na seleção de dados do TreeView Simples no databasejoin

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/databasejoin#12]
**Passo a passo do erro:**

**1.** Selecionar que o render do elemento seja 'TreeView Simples' no painel de controle.
**2.** Ao fazer um novo registro na lista, adicionar uma opção entre os dados organizados no 'TreeView Simples'.
**3.** Antes de salvar o novo registro, cancelar a opção selecionada no passo 2.
**4.** Ao excluir a opção selecionada, não é permitido selecionar uma nova.

**Comment by karinepires6** [comment]
Resolved in 97598c8
