### ISSUE TITLE
Erro na função concatenar rótulo

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/databasejoin#16]
Erro:

- Neste caso, existe o elemento Release que vai trazer como rótulo a versão específica de determinado Produto.
![image](https://user-images.githubusercontent.com/57194130/68505562-482b8780-0246-11ea-848b-7001266f8125.png)
- Porém, além dela, com a função de concatenar, após selecionar a versão, deveria aparecer tantoas opções da lista Produto e assim juntar as duas informações.
![image](https://user-images.githubusercontent.com/57194130/68505584-5da0b180-0246-11ea-9fcd-dfdcff3e87be.png)

**Comment by karinepires6** [comment]
Resolved in commit 3dbac1d
