### ISSUE TITLE
Erro em adicionar novas opções em um grupo repetitivo com databasejoin MultiSelect Autocomplete

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/databasejoin#17]
Erro:

- Durante o teste, tenho um grupo repetitivo 'Testes Realizados' vinculado com a minha lista 'Teste'.
-  Dentro do grupo repetitivo, tenho um elemento 'Requisito ou Bug Gerado', onde o plugin utilizado é o databasejoin
![image](https://user-images.githubusercontent.com/57194130/68505896-1f57c200-0247-11ea-9bab-4d626bf18997.png)
- Quando seleciono como render a opção 'MultiSelect List', consigo registrar o primeiro dado no elemento 'Requisito ou Bug Gerado', mas ao adicionar mais um 'Teste Realizado', ele traz o que foi marcado anteriormente e não deixa ser possível editar a opção selecionada no primeiro registro.
![Apresentação sem título](https://user-images.githubusercontent.com/57194130/68506304-1d423300-0248-11ea-8ba5-62c72bd0ff17.png)

**Comment by karinepires6** [comment]
A atual implementação dos renderes Treeview Simples / Multiselect Treeview / Multiselect Autocomplete não satisfaz as condições que o Fabrik atualmente utiliza no repeat group.
Para essa tarefa seria necessário reimplementar os renderes da mesma forma que os renderes de checkbox/radio button foi implementado, pois a função **duplicateGroup** pega os elementos HTML gerados pelo render e adiciona um novo atributo id e name utilizando a classe css fabrikinput.

O problema é que os novos renderes foram baseados nos renderes em funcionamento do databasejoin e quando a função duplicateGroup é chamada ela não consegue duplicar corretamente os atributos necessários dos inputs gerados no render. Para resolver isso é necessário mudar a implementação destes renderes no front-end e no back-end seguindo a mesma implementação dos renderes nativos do databasejoin para que a função duplicateGroup entenda o elemento HTML e duplique corretamente cada componente necessário.

NOTAS:
A função duplicateGroup se encontra no arquivo em /media/com_fabrik/js/dist/form.js

**Comment by karinepires6** [comment]
![IMG_20191119_155650](https://user-images.githubusercontent.com/19169609/69177092-ae859500-0ae5-11ea-9e9e-0752d3cdf3cb.jpg)
![IMG_20191119_155636](https://user-images.githubusercontent.com/19169609/69177100-afb6c200-0ae5-11ea-8b1e-1b3a74f8fd07.jpg)
