### ISSUE TITLE
Bug ao adicionar novo registro no databasejoin 0.1.5

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/databasejoin#19]
Erro:

- Colocando a opção 'Render' - Árvore / Autocompletar com Estilo Apenas a árvore, ao adicionar um novo registro, aparece uma na tela como visto no Elemento ‘Assunto’ (como se já houvesse alguma seleção feita). Mas é somente apagar o que está selecionado e escolher outra opção normalmente.

![image](https://user-images.githubusercontent.com/57194130/68692167-c42e1400-0553-11ea-865b-6d308d1ffc70.png)

- O mesmo acontece com a configuração 'Render' - Árvore / Autocompletar com Estilo Ambos

![image](https://user-images.githubusercontent.com/57194130/68692387-2c7cf580-0554-11ea-8721-6a126e76ce3d.png)

**Comment by karinepires6** [comment]
Resolved in commit 3dbac1d
