### ISSUE TITLE
Falha na busca de palavras acentuadas

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/databasejoin#21]
Erro:

- A 'Busca' não está encontrando palavras acentuadas

- COM ACENTO:
![Com acento](https://user-images.githubusercontent.com/57194130/68882398-d93eaa80-06ed-11ea-9a0a-7993d8fb82b5.png)

-SEM ACENTO:
![Sem acento](https://user-images.githubusercontent.com/57194130/68882430-e6f43000-06ed-11ea-97c6-3cbb5f6b9d69.png)

**Comment by karinepires6** [comment]
http://fabrikar.com/forums/index.php?threads/accented-characters-in-list-filter.50992/

**Comment by karinepires6** [comment]
@hugocalvet, a pesquisa com palavras sem acento funciona quando a propriedade da imagem abaixo está atribuída como 'Sim'.
![imgfilter](https://user-images.githubusercontent.com/19169609/69261558-8870fb00-0ba0-11ea-95a9-33824c9462f9.png)
